kind: workflow
trigger:
  kind: OnConversationStart
  id: trigger_wf
  actions:
    - kind: InvokeAzureAgent
      id: step_generate
      agent:
        name: integration-pulse-solace-publisher
      conversationId: =System.ConversationId
      input:
        messages: =System.LastMessage.Text
      output:
        autoSend: true
id: ""
name: solace-generate-workflow
